[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Netlify'ın build sırasında dosyaları tarayıp build'i durdurmasını engeller
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  NODE_VERSION = "22.22.0"